### ISSUE TITLE
Model for object element not loadable (mesh is empty)

### ISSUE THREAD

**Issue by JaXt0r** [GothicKit/phoenix-shared-interface#19]
When loading an object's model, I get no nullptr, but the model itself has no data.

Example:
```c++
auto mdm = pxMdmLoadFromVdf(vdfPtr, name);
auto checksum = pxMdmGetChecksum(mdm); // 0
auto meshCount = pxMdmGetMeshCount(mdm); // 0
...
```

It cab be tested with `CHESTBIG_OCCHESTLARGE.MDM` from _anims.vdf_

C# Debugger output of phoenix-csharp-interface
![image](https://user-images.githubusercontent.com/120568393/235643986-a9af433c-56b9-4e11-978f-d7a03268c7f8.png)

**Comment by JaXt0r** [comment]
I tested with mdl files. It's the same: ModelMesh is empty if loaded. (e.g. "BEDLOW_PC.ASC")

![image](https://user-images.githubusercontent.com/120568393/236012492-14132d24-414b-4adc-bef4-2ab34baf1ce5.png)

**Comment by lmichaelis** [comment]
I can't reproduce this problem. When I load the file, yes the checksum is `0` and there are no meshes but there are attachments. So basically, this specific file just doesn't have a mesh itself, it just has attachments.

![bilde](https://user-images.githubusercontent.com/20187490/236119363-40f96c09-da2a-472c-8e8d-d03dfd7c2e22.png)

**Comment by JaXt0r** [comment]
Ah ok. This might make sense. Thank you.

Can you please help with the attachments then. Currently when requesting them I need to know the string-keys beforehand. But it would be great to get them indexed or at least all the keys to request the values. Otherwise I don't really know what keys to request.

**Comment by lmichaelis** [comment]
I'm not sure how to use them either but the names look like they're model hierarchy node names. Maybe they're attached to the nodes and move with them?

**Comment by JaXt0r** [comment]
Good point. And thank you for the screenshot. This helps me checking further.

**Comment by JaXt0r** [comment]
Thank you for your support. You were right. The mdl.attachment keys are stored inside mdm.bones[].name. This helped. I can now load the right meshes from attachments.
