### ISSUE TITLE
Export function to get uncompressed Textures.

### ISSUE THREAD

**Issue by JaXt0r** [GothicKit/phoenix-shared-interface#3]
The API currently supports returning compressed Textures only.

```c++
PXC_API uint8_t const* pxTexGetMipmap(PxTexture const* tex, uint32_t* length, uint32_t level, uint32_t* width, uint32_t* height);
```
(https://github.com/GothicKit/phoenix-shared-interface/blob/main/include/phoenix/cffi/Texture.h#L46)

As not every game engine supports all the compression algorithms, we need to have a way getting the data uncompressed if needed.
(Specifically Unity3D can't handle dxt_3)

OpenGothic uses it like this:
```c++
      if (tex.format() == phoenix::tex_dxt1 ||
          tex.format() == phoenix::tex_dxt5) {
              ...
        } else {
            auto rgba = tex.as_rgba8(0); // This is the required method to call.
        }
```
https://github.com/Try/OpenGothic/blob/c648801ff216974e0756d162e1b8087a2b5f576e/game/resources.cpp#L304

It would be sufficient to either have another parameter like ```bool uncompressed``` or call a similar method like ```pxTexGetMipmapUncompressed()```

**Comment by lmichaelis** [comment]
What do you think about this?
```c
typedef void (*PxTexDecompressCallback)(uint8_t const* data, uint32_t size, void* context);
void pxTexDecompress(PxTexture const* tex, PxTexDecompressCallback cb, void* context);
```

This would automatically allocate the `data` buffer and free it after the callback exits. You'd use it like this:

```c
void copyTexture(uint8_t const* data, uint32_t size, void* context) {
   uint8_t** output = context;
   *output = malloc(size);
   memcpy(*output, data, size);
}

int main() {
   uint8_t* data;
   pxTexDecompress(tex, copyTexture, &data);


   // Now `data` contains the decompressed image data.
   free(data);
}
```

**Comment by JaXt0r** [comment]
Thanks for your idea. But I would like to avoid callbacks as it adds a new architecture pattern you only use for Vm right now (where it definitely makes sense).

On C# interface I already build small wrapper functions which take care of loading, transforming, and deleting C-data. No need for callbacks.

How about using it the classical way? Something like:

```c++
PXC_API uint8_t const* pxTexGetMipmapUncompressed(PxTexture const* tex, uint32_t* length, uint32_t level, uint32_t* width, uint32_t* height) {
    ...
}
```

Normal flow for C# sharp is right now:
1. Get TextureMetadata - exists
2. Decide whether to call pxTexGetMipmap() or pxTexGetMipmapUncompressed() based on TextureFormat - second half is new
3. Then call pxTexMipmapUncompressedDestroy() if uncompressed data was received before. - new
